export const defaultCities = [
  { name: "Cali", countryCode: "CO" },
  { name: "Palmira", countryCode: "CO" },
  { name: "Buenaventura", countryCode: "CO" },
  { name: "Tuluá", countryCode: "CO" },
  { name: "Cartago", countryCode: "CO" },
  { name: "Buga", countryCode: "CO" },
  { name: "Jamundí", countryCode: "CO" },
  { name: "Yumbo", countryCode: "CO" },
];

export const defaultCategories = [
  { name: "Cocina colombiana", slug: "cocina-colombiana" },
  { name: "Cocina valluna", slug: "cocina-valluna" },
  { name: "Cocina del Pacífico", slug: "cocina-del-pacifico" },
  { name: "Cocina costeña", slug: "cocina-costena" },
  { name: "Cocina paisa", slug: "cocina-paisa" },
  { name: "Cocina llanera", slug: "cocina-llanera" },
  { name: "Cocina de autor", slug: "cocina-de-autor" },
  { name: "Cocina fusión", slug: "cocina-fusion" },
  { name: "Gourmet", slug: "gourmet" },
  { name: "Buffet", slug: "buffet" },
  { name: "Parrilla", slug: "parrilla" },
  { name: "Asados", slug: "asados" },
  { name: "Carnes", slug: "carnes" },
  { name: "BBQ", slug: "bbq" },
  { name: "Pollo", slug: "pollo" },
  { name: "Alitas", slug: "alitas" },
  { name: "Hamburguesas", slug: "hamburguesas" },
  { name: "Pizza", slug: "pizza" },
  { name: "Pasta", slug: "pasta" },
  { name: "Sándwiches", slug: "sandwiches" },
  { name: "Wraps", slug: "wraps" },
  { name: "Perros calientes", slug: "perros-calientes" },
  { name: "Salchipapas", slug: "salchipapas" },
  { name: "Empanadas", slug: "empanadas" },
  { name: "Arepas", slug: "arepas" },
  { name: "Fritos", slug: "fritos" },
  { name: "Antojitos", slug: "antojitos" },
  { name: "Comida rápida", slug: "comida-rapida" },
  { name: "Street food", slug: "street-food" },
  { name: "Desayunos", slug: "desayunos" },
  { name: "Brunch", slug: "brunch" },
  { name: "Cafetería", slug: "cafeteria" },
  { name: "Café de especialidad", slug: "cafe-de-especialidad" },
  { name: "Panadería", slug: "panaderia" },
  { name: "Pastelería", slug: "pasteleria" },
  { name: "Postres", slug: "postres" },
  { name: "Helados", slug: "helados" },
  { name: "Bebidas", slug: "bebidas" },
  { name: "Jugos y smoothies", slug: "jugos-y-smoothies" },
  { name: "Saludable", slug: "saludable" },
  { name: "Vegetariana", slug: "vegetariana" },
  { name: "Vegana", slug: "vegana" },
  { name: "Sin gluten", slug: "sin-gluten" },
  { name: "Keto", slug: "keto" },
  { name: "Fit", slug: "fit" },
  { name: "Ensaladas", slug: "ensaladas" },
  { name: "Bowl", slug: "bowl" },
  { name: "Sopas", slug: "sopas" },
  { name: "Mariscos", slug: "mariscos" },
  { name: "Pescados", slug: "pescados" },
  { name: "Ceviches", slug: "ceviches" },
  { name: "Arroces", slug: "arroces" },
  { name: "Comida mexicana", slug: "comida-mexicana" },
  { name: "Tex-Mex", slug: "tex-mex" },
  { name: "Tacos", slug: "tacos" },
  { name: "Burritos", slug: "burritos" },
  { name: "Comida italiana", slug: "comida-italiana" },
  { name: "Comida mediterránea", slug: "comida-mediterranea" },
  { name: "Comida española", slug: "comida-espanola" },
  { name: "Comida francesa", slug: "comida-francesa" },
  { name: "Comida griega", slug: "comida-griega" },
  { name: "Comida alemana", slug: "comida-alemana" },
  { name: "Comida británica", slug: "comida-britanica" },
  { name: "Comida americana", slug: "comida-americana" },
  { name: "Comida caribeña", slug: "comida-caribena" },
  { name: "Comida peruana", slug: "comida-peruana" },
  { name: "Comida argentina", slug: "comida-argentina" },
  { name: "Comida brasileña", slug: "comida-brasilena" },
  { name: "Comida venezolana", slug: "comida-venezolana" },
  { name: "Comida ecuatoriana", slug: "comida-ecuatoriana" },
  { name: "Comida chilena", slug: "comida-chilena" },
  { name: "Comida uruguaya", slug: "comida-uruguaya" },
  { name: "Comida cubana", slug: "comida-cubana" },
  { name: "Comida dominicana", slug: "comida-dominicana" },
  { name: "Comida puertorriqueña", slug: "comida-puertorriquena" },
  { name: "Comida china", slug: "comida-china" },
  { name: "Comida japonesa", slug: "comida-japonesa" },
  { name: "Sushi", slug: "sushi" },
  { name: "Ramen", slug: "ramen" },
  { name: "Comida coreana", slug: "comida-coreana" },
  { name: "Comida tailandesa", slug: "comida-tailandesa" },
  { name: "Comida vietnamita", slug: "comida-vietnamita" },
  { name: "Comida india", slug: "comida-india" },
  { name: "Comida turca", slug: "comida-turca" },
  { name: "Comida árabe", slug: "comida-arabe" },
  { name: "Comida libanesa", slug: "comida-libanesa" },
  { name: "Comida marroquí", slug: "comida-marroqui" },
  { name: "Comida etíope", slug: "comida-etiope" },
  { name: "Comida africana", slug: "comida-africana" },
  { name: "Comida internacional", slug: "comida-internacional" },
];
